{
  "formatVersion": "1.1",
  "component": {
    "group": "zh.qiushui.mod.core",
    "module": "qs-lib-common",
    "version": "1.0.2+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qs-lib-common-1.0.2+1.20.1.jar",
          "url": "qs-lib-common-1.0.2+1.20.1.jar",
          "size": 8188,
          "sha512": "e13c6a8d609f8099aca137d3534a1984a11d9f69dc148987271ae47fb1829a599bba6931829b2e420375d582f41206b2d10405ce0b139bc6e9648bd8340d9c65",
          "sha256": "f5666bc7d3026a4be90a829e3f2a5e3f27dd9ac6dae92fb7d60bb3ce0a3204e3",
          "sha1": "415b549688ced4317ffc49ecda9f3be8038be797",
          "md5": "87eb105542ddbd5787a96826ff58a2d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "qs-lib-common-1.0.2+1.20.1.jar",
          "url": "qs-lib-common-1.0.2+1.20.1.jar",
          "size": 8188,
          "sha512": "e13c6a8d609f8099aca137d3534a1984a11d9f69dc148987271ae47fb1829a599bba6931829b2e420375d582f41206b2d10405ce0b139bc6e9648bd8340d9c65",
          "sha256": "f5666bc7d3026a4be90a829e3f2a5e3f27dd9ac6dae92fb7d60bb3ce0a3204e3",
          "sha1": "415b549688ced4317ffc49ecda9f3be8038be797",
          "md5": "87eb105542ddbd5787a96826ff58a2d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qs-lib-common-1.0.2+1.20.1-sources.jar",
          "url": "qs-lib-common-1.0.2+1.20.1-sources.jar",
          "size": 4897,
          "sha512": "d47c99b4df8cfa7210a1d3af78cab965d0410c83ec9f02636b2f343217cbdab5c4bbd59842881bcc91f408478e9dd78a440c8a2880547d6096ad6e41c48ae570",
          "sha256": "8236c6afcb8f946e17bb4c72027f407b00b1c2205c93ef272ec99d6909b16fbf",
          "sha1": "d38940c627751c47c2c68c6d8c3beaee0afda990",
          "md5": "784517b262a146f989435c5a7e390b7d"
        }
      ]
    }
  ]
}
