{
  "formatVersion": "1.1",
  "component": {
    "group": "zh.qiushui.mod",
    "module": "zakuro",
    "version": "1.0.1.1+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "zakuro-1.0.1.1+1.20.1.jar",
          "url": "zakuro-1.0.1.1+1.20.1.jar",
          "size": 318965,
          "sha512": "971992d8aa84b2a2897e6c4ad33df2efdbd8229f2af87b3afd363b2d3a660236fb33770d0251d82a8861edf1deb49d677e70d1f69c232192c1ef1f19d22b4511",
          "sha256": "9161904006f784039c995c50313d7c53235d158381c7956c7f942268c41484a8",
          "sha1": "e9bf15788fe6af335a83596cbd1637bd47fbcfd4",
          "md5": "7d0fb24c56a3434e03a0196e3e028d16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "zh.qiushui.mod",
          "module": "core-lib",
          "version": {
            "requires": "1.0.1.4+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.118"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "zakuro-1.0.1.1+1.20.1.jar",
          "url": "zakuro-1.0.1.1+1.20.1.jar",
          "size": 318965,
          "sha512": "971992d8aa84b2a2897e6c4ad33df2efdbd8229f2af87b3afd363b2d3a660236fb33770d0251d82a8861edf1deb49d677e70d1f69c232192c1ef1f19d22b4511",
          "sha256": "9161904006f784039c995c50313d7c53235d158381c7956c7f942268c41484a8",
          "sha1": "e9bf15788fe6af335a83596cbd1637bd47fbcfd4",
          "md5": "7d0fb24c56a3434e03a0196e3e028d16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zakuro-1.0.1.1+1.20.1-sources.jar",
          "url": "zakuro-1.0.1.1+1.20.1-sources.jar",
          "size": 296774,
          "sha512": "158251611ffa8c9957c7a3fb20d3cd361526218ed6bdc9d0281b7330a9b8539720dab779e2c14d49515652c6e49cc0e53c076aaea712a484c63a54d104e36d22",
          "sha256": "098a749fed2b7375c1de624d9195feb99e9fc0ecfb492c9b9c9cc80ccdd252c8",
          "sha1": "f621c5b140d4a954881ccfa3061770fd5c7cd743",
          "md5": "743eb43bab5759a641f8a5078e4920f8"
        }
      ]
    }
  ]
}
