{
  "formatVersion": "1.1",
  "component": {
    "group": "zh.qiushui.mod",
    "module": "core-lib",
    "version": "1.0.1.5+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.118"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-lib-1.0.1.5+1.20.1.jar",
          "url": "core-lib-1.0.1.5+1.20.1.jar",
          "size": 13346,
          "sha512": "ce9a66acde9c1d1fa980b6d9f5fb7fe62a034a599be2d9f514674cd8ad79c2e0f902d69c37d9dcdfa4b786c034759c7acd0b81b399f96b8dec91f6958f41c055",
          "sha256": "9ba19929d3a18b40eb6614bb58c1444258dbf3f0a7ba98a02280c635b431aebb",
          "sha1": "382fb9838a0dd6c056c34d979216c7a33a619ae8",
          "md5": "5cd0b9fe3ca43c6d69e53e49a09b519b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-lib-1.0.1.5+1.20.1.jar",
          "url": "core-lib-1.0.1.5+1.20.1.jar",
          "size": 13346,
          "sha512": "ce9a66acde9c1d1fa980b6d9f5fb7fe62a034a599be2d9f514674cd8ad79c2e0f902d69c37d9dcdfa4b786c034759c7acd0b81b399f96b8dec91f6958f41c055",
          "sha256": "9ba19929d3a18b40eb6614bb58c1444258dbf3f0a7ba98a02280c635b431aebb",
          "sha1": "382fb9838a0dd6c056c34d979216c7a33a619ae8",
          "md5": "5cd0b9fe3ca43c6d69e53e49a09b519b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-lib-1.0.1.5+1.20.1-sources.jar",
          "url": "core-lib-1.0.1.5+1.20.1-sources.jar",
          "size": 10219,
          "sha512": "23a10c5cad3f74455d5e03dbe6e4e4db66fa880c1db6e6d3ec5e2d1a1be4a20fbed8ef3d347fd111ee39762b974cf87a32594ba5920e4c7ac3b44c25997ebdf4",
          "sha256": "88a098f07444b145af7ab78d993c16ede8315a2986a8efdaaf0412086766ed11",
          "sha1": "028c059b5a0e0feedeb3f8f40089791470114399",
          "md5": "7f22915013ce27148389abb7b86957a0"
        }
      ]
    }
  ]
}
