{
  "formatVersion": "1.1",
  "component": {
    "group": "zh.qiushui.mod",
    "module": "zakuro",
    "version": "1.0.1.3+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "zakuro-1.0.1.3+1.20.1.jar",
          "url": "zakuro-1.0.1.3+1.20.1.jar",
          "size": 754501,
          "sha512": "6b90071e71eea5a17c151c8024c5fbacbe0f9777c302133819289b4511f1c83f5a471f7010c1800c9e84b6f3676b865d6a26fc735eeab42c291bd64510ffeadf",
          "sha256": "923ef69b3adf4e4163c2654d65e2d65652b1ff03875e0a69999c99514f1d9321",
          "sha1": "71d887d619443c1ca6b0a300832ed5f18d987d20",
          "md5": "779047eadabb4f26dd0db331a2776d36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "zh.qiushui.mod",
          "module": "core-lib",
          "version": {
            "requires": "1.0.1.5+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.118"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "zakuro-1.0.1.3+1.20.1.jar",
          "url": "zakuro-1.0.1.3+1.20.1.jar",
          "size": 754501,
          "sha512": "6b90071e71eea5a17c151c8024c5fbacbe0f9777c302133819289b4511f1c83f5a471f7010c1800c9e84b6f3676b865d6a26fc735eeab42c291bd64510ffeadf",
          "sha256": "923ef69b3adf4e4163c2654d65e2d65652b1ff03875e0a69999c99514f1d9321",
          "sha1": "71d887d619443c1ca6b0a300832ed5f18d987d20",
          "md5": "779047eadabb4f26dd0db331a2776d36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zakuro-1.0.1.3+1.20.1-sources.jar",
          "url": "zakuro-1.0.1.3+1.20.1-sources.jar",
          "size": 306855,
          "sha512": "4e6556bb99ae82886e352d0204a76fd7936ec12ef5d1ff3cee5ad0c2c778c04cdf4f7383a1583d56898abf51106a28e46d17cf5b034a54f92ca45113e96f0579",
          "sha256": "59d73b76c3ce66d100a158627a770a8967ea3c49bb2589b709c399f726b1ddbf",
          "sha1": "6605e63179ba1c34bf909dd5679df36a9b333f32",
          "md5": "7b66da899ae7609021582ce453b47a46"
        }
      ]
    }
  ]
}
