{
  "formatVersion": "1.1",
  "component": {
    "group": "zh.qiushui.mod",
    "module": "zakuro",
    "version": "1.0.1.3+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "zakuro-1.0.1.3+1.20.1.jar",
          "url": "zakuro-1.0.1.3+1.20.1.jar",
          "size": 766207,
          "sha512": "3ecf0be9d6c006ff86068cc119d59db84c3831c983fc942721ed936d9fa2014ab75663a7e8fd3fe8bd0d6b868785b488f7d67570476fe4fdd07a778732d3f139",
          "sha256": "cd5e65e7a8b49e3d406b11e40f6f4c7a6e3443086f984cfd41e096ef90c3152b",
          "sha1": "94a79e13f25e52f87f8deb2e3d9c832e07eb311b",
          "md5": "e78446fdd23b0170cd5b313753b4a5e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "zh.qiushui.mod",
          "module": "core-lib",
          "version": {
            "requires": "1.0.1.5+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.118"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "zakuro-1.0.1.3+1.20.1.jar",
          "url": "zakuro-1.0.1.3+1.20.1.jar",
          "size": 766207,
          "sha512": "3ecf0be9d6c006ff86068cc119d59db84c3831c983fc942721ed936d9fa2014ab75663a7e8fd3fe8bd0d6b868785b488f7d67570476fe4fdd07a778732d3f139",
          "sha256": "cd5e65e7a8b49e3d406b11e40f6f4c7a6e3443086f984cfd41e096ef90c3152b",
          "sha1": "94a79e13f25e52f87f8deb2e3d9c832e07eb311b",
          "md5": "e78446fdd23b0170cd5b313753b4a5e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zakuro-1.0.1.3+1.20.1-sources.jar",
          "url": "zakuro-1.0.1.3+1.20.1-sources.jar",
          "size": 317773,
          "sha512": "1b73c838194f535f93099c5fc1c2c7d4367b52c5764c6f46407c673e3d831222499684641b7e6f9a245589339a21fc4f557d3cf31dc39025d9a93590d1ef1ff5",
          "sha256": "58889f500e92ee94a39418be8bdb766cd550d4e66b5f2e1bc4330f91b84fc128",
          "sha1": "09f7bfb60814f80236f49a5b5d6476b9634f727e",
          "md5": "41e10464fdf0b552281821490d532f5d"
        }
      ]
    }
  ]
}
