{
  "formatVersion": "1.1",
  "component": {
    "group": "zh.qiushui.mod",
    "module": "zakuro",
    "version": "1.0.1.3+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "zakuro-1.0.1.3+1.20.1.jar",
          "url": "zakuro-1.0.1.3+1.20.1.jar",
          "size": 754493,
          "sha512": "f274cb5c086d5e5e646768e82e7c08478ad02ce74d5631ec13bfcaa5cf0a5e94978073bdd46c5c0fb211030f7e3e616688a89caa894b80d9c60882a218b8c4fa",
          "sha256": "4279893a2742ac043518a2234d220ff99a4979ba54d3837b48d04458d6357661",
          "sha1": "e3aefacb9d46808d5f725dc115da6e3f2e8ddb9c",
          "md5": "489640993aaac61f499854da6152a2b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "zh.qiushui.mod",
          "module": "core-lib",
          "version": {
            "requires": "1.0.1.5+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.118"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "zakuro-1.0.1.3+1.20.1.jar",
          "url": "zakuro-1.0.1.3+1.20.1.jar",
          "size": 754493,
          "sha512": "f274cb5c086d5e5e646768e82e7c08478ad02ce74d5631ec13bfcaa5cf0a5e94978073bdd46c5c0fb211030f7e3e616688a89caa894b80d9c60882a218b8c4fa",
          "sha256": "4279893a2742ac043518a2234d220ff99a4979ba54d3837b48d04458d6357661",
          "sha1": "e3aefacb9d46808d5f725dc115da6e3f2e8ddb9c",
          "md5": "489640993aaac61f499854da6152a2b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zakuro-1.0.1.3+1.20.1-sources.jar",
          "url": "zakuro-1.0.1.3+1.20.1-sources.jar",
          "size": 306850,
          "sha512": "498cc3d2c3409a3b7e77e8b8d07118d991ad6cfba2ca38ff4d4ce5be376b08029a5afcc55e23a87dbe46ec482b491ed2db8fb08827b5c2cee459f574f1d154a3",
          "sha256": "3604c9023beb019ccaf4ef7039b62cc1d28cc4d1dd8137713f8c7ca6cf3218ed",
          "sha1": "306231e199120f277862bc05c70f11b8e5185ec2",
          "md5": "c2d8b710ba992b94291cad7c0f23dfcd"
        }
      ]
    }
  ]
}
