{
  "formatVersion": "1.1",
  "component": {
    "group": "zh.qiushui.mod",
    "module": "zakuro",
    "version": "1.0.0.2+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "zakuro-1.0.0.2+1.20.1.jar",
          "url": "zakuro-1.0.0.2+1.20.1.jar",
          "size": 29840,
          "sha512": "ad30dda0a53af38e98f44cf046e1a06b728efd9789afd375884ead51c9f049bfc44df37048f09d5070264dc204499a07234b85e946bdb362bb0d555fc9d089cd",
          "sha256": "2191883b048d1bbfa2a314312084b8679d1847bf5a7df0084d0fd9f909b780d2",
          "sha1": "67f4a7e96889696be445235c0936ee24d83eea2e",
          "md5": "80722146b1199d210bbe10812988b0ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.118"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "zakuro-1.0.0.2+1.20.1.jar",
          "url": "zakuro-1.0.0.2+1.20.1.jar",
          "size": 29840,
          "sha512": "ad30dda0a53af38e98f44cf046e1a06b728efd9789afd375884ead51c9f049bfc44df37048f09d5070264dc204499a07234b85e946bdb362bb0d555fc9d089cd",
          "sha256": "2191883b048d1bbfa2a314312084b8679d1847bf5a7df0084d0fd9f909b780d2",
          "sha1": "67f4a7e96889696be445235c0936ee24d83eea2e",
          "md5": "80722146b1199d210bbe10812988b0ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zakuro-1.0.0.2+1.20.1-sources.jar",
          "url": "zakuro-1.0.0.2+1.20.1-sources.jar",
          "size": 19875,
          "sha512": "0b985249e968dd92e0ec3c863d254fc93a5c6142828658e079f9f74e01e3c807918d88a1def3b053c69879f413701c4081590d137173b8c14496081c29e0626e",
          "sha256": "6b808c12caf8b3f86c3708a86e3f66bb221fdfff8e81f2735f9effaa984f2d67",
          "sha1": "6e027b536dea8ea5e79e3c13c0f01b44df520702",
          "md5": "812c4cf5a8cf3a8b2370d7fc19c71c4c"
        }
      ]
    }
  ]
}
